// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2VUahw0J3HAN2-lsmtLYFXOFmRMEctLU',
    appId: '1:900764331858:web:c04ba87c4a8ab454a7148b',
    messagingSenderId: '900764331858',
    projectId: 'domovina-development',
    authDomain: 'domovina-development.firebaseapp.com',
    storageBucket: 'domovina-development.firebasestorage.app',
    measurementId: 'G-Z1F4NF02T7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCNNtISti4BegzX3pM3EOhe9p6O29S8v0',
    appId: '1:900764331858:android:2f5d27ea80b5a7aea7148b',
    messagingSenderId: '900764331858',
    projectId: 'domovina-development',
    storageBucket: 'domovina-development.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQlYUPK39ECehtSV9IpTAPW0se3pxFcTU',
    appId: '1:900764331858:ios:1ab2c4cccc37df75a7148b',
    messagingSenderId: '900764331858',
    projectId: 'domovina-development',
    storageBucket: 'domovina-development.firebasestorage.app',
    iosClientId: '900764331858-qko12cfvcnmdrtdrd7qa9uhpqov573am.apps.googleusercontent.com',
    iosBundleId: 'hr.spremni.domovina.wallet',
  );
}
